pub mod anilist_service;
mod anilist_service_test;
pub mod archive_service;
mod archive_service_test;
pub mod book_service;
mod book_service_test;
pub mod collectionner_service;
mod collectionner_service_test;
pub mod converter_service;
mod converter_service_test;
pub mod googlebooks_service;
mod googlebooks_service_test;
pub mod marvel_service;
mod marvel_service_test;
pub mod openlibrary_service;
mod openlibrary_service_test;
pub mod profile_service;
mod profile_service_test;
